branch-defaults:
  default:
    environment: futurity-frontend-prod
    group_suffix: null
  staging:
    environment: futurity-frontend-prod
global:
  application_name: futurity-frontend
  branch: null
  default_ec2_keyname: developement
  default_platform: Docker running on 64bit Amazon Linux 2023
  default_region: eu-west-3
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
