import React, { useState } from 'react';
import { visualizationService } from '../../../services/visualizationService';
import type { FutureGrapherParams, FutureGrapherResult } from '../../../services/visualizationService';

// Basic styling (consistent with other vanilla cards)
const styles: { [key: string]: React.CSSProperties } = {
  card: {
    border: '1px solid #ddd',
    padding: '16px',
    borderRadius: '8px',
    minWidth: '300px',
    maxWidth: '380px',
    background: '#e6f7ff', // Light cyan background
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
  },
  formControl: {
    marginBottom: '12px',
  },
  label: {
    display: 'block',
    fontSize: '14px',
    fontWeight: 'bold',
    marginBottom: '4px',
  },
  textarea: {
    width: '100%',
    padding: '8px',
    fontSize: '14px',
    border: '1px solid #ccc',
    borderRadius: '4px',
    minHeight: '80px',
    boxSizing: 'border-box',
  },
  button: {
    padding: '10px 15px',
    fontSize: '14px',
    color: 'white',
    backgroundColor: '#007bff', // Standard blue
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    marginTop: 'auto', // Pushes button to the bottom
  },
  buttonLoading: {
    backgroundColor: '#6c757d', // Grey when loading
  },
  error: {
    color: 'red',
    fontSize: '12px',
    marginTop: '8px',
    whiteSpace: 'pre-wrap',
  },
  resultContainer: {
    marginTop: '12px',
    maxHeight: '300px',
    overflowY: 'auto',
    border: '1px solid #ddd',
    padding: '10px',
    background: '#fff',
  },
  resultImage: {
    maxWidth: '100%',
    height: 'auto',
    borderRadius: '4px',
    marginTop: '8px',
  },
  h5: {
    fontSize: '1.25em',
    fontWeight: 'bold',
    color: '#0056b3', // Darker blue for title
    marginBottom: '8px',
  },
  pDescription: {
    fontSize: '12px',
    color: '#555',
    lineHeight: '1.4',
    marginBottom: '12px',
  },
  pInputInfo: {
    fontSize: '11px',
    color: '#007bff', // Blue for input type
    marginBottom: '10px',
  },
};

const FutureGrapherToolCard: React.FC = () => {
  const [prompt, setPrompt] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [result, setResult] = useState<FutureGrapherResult | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleRunTool = async (event: React.FormEvent) => {
    event.preventDefault();
    if (!prompt.trim()) {
      setError('Please enter a prompt for the image.');
      return;
    }

    setIsLoading(true);
    setResult(null);
    setError(null);

    try {
      const params: FutureGrapherParams = { prompt };
      const response = await visualizationService.runFutureGrapher(params);
      setResult(response);
      if (response.error) {
        setError(response.error);
      }
    } catch (e: any) {
      setError(e.message || 'Failed to generate image. Please try again.');
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div style={styles.card}>
      <h5 style={styles.h5}>FutureGrapher</h5>
      <p style={styles.pDescription}>
        Generate an image based on your textual prompt using advanced AI models. Describe a scene, concept, or idea, and see it visualized.
      </p>
      <p style={styles.pInputInfo}>
        Input: Text prompt describing the desired image.
      </p>

      <form onSubmit={handleRunTool} style={{ display: 'flex', flexDirection: 'column', flexGrow: 1, minHeight: 0 }}>
        <div style={styles.formControl}>
          <label htmlFor='futureGrapherPrompt' style={styles.label}>Image Prompt:</label>
          <textarea
            id='futureGrapherPrompt'
            value={prompt}
            onChange={(e) => setPrompt(e.target.value)}
            placeholder='e.g., A futuristic city skyline at sunset with flying vehicles'
            style={styles.textarea}
            rows={3}
          />
        </div>

        <button
          type="submit"
          style={{ ...styles.button, ...(isLoading ? styles.buttonLoading : {}) }}
          disabled={isLoading}
        >
          {isLoading ? 'Generating Image...' : 'Generate Image'}
        </button>
      </form>

      {error && (
        <div style={styles.error}>
          <strong>Error:</strong> {error}
        </div>
      )}

      {result && (
        <div style={styles.resultContainer}>
          <h6 style={{ fontSize: '1em', fontWeight: 'bold', marginTop: '10px' }}>Generated Image:</h6>
          {result.message && <p style={{ fontSize: '12px', color: result.error ? 'red': 'green' }}>{result.message}</p>}
          {result.image_url && (
            <img src={result.image_url} alt="Generated by FutureGrapher" style={styles.resultImage} />
          )}
          {!result.image_url && !result.error && !isLoading && (
             <p style={{fontSize: '12px', marginTop: '10px'}}>No image was returned, but the process completed.</p>
          )}
        </div>
      )}
    </div>
  );
};

export default FutureGrapherToolCard;