import type { AnalysisType } from '../types';

// Helper functions for horizon chart
export const convertHorizonValue = (horizon: number): 1 | 2 | 3 | 4 => {
  if (horizon <= 0.25) return 4; // Idea
  if (horizon <= 0.5) return 3; // Science
  if (horizon <= 0.75) return 2; // Engineering
  return 1; // Business
};

export const getCategoryNumber = (
  categoryName: string,
  categoryNames: string[]
): 1 | 2 | 3 | 4 | 5 => {
  const index = categoryNames.indexOf(categoryName);
  const categoryNum = index >= 0 ? index + 1 : 1;
  // Ensure we return a value within the expected range
  return Math.min(categoryNum, 5) as 1 | 2 | 3 | 4 | 5;
};

// Generate mock analysis result based on type
export const generateMockAnalysisResult = (
  analysisType: AnalysisType,
  selectedSubjectNames: string[],
  excludeTermsList: string[],
  selectedSubjectsCount: number
): string => {
  const timestamp = new Date().toLocaleString();

  switch (analysisType) {
    case 'patent':
      return `PATENT LANDSCAPE ANALYSIS REPORT
Generated: ${timestamp}

ANALYSIS SCOPE:
Subjects Analyzed: ${selectedSubjectNames.join(', ')}
${
  excludeTermsList.length > 0
    ? `Excluded Terms: ${excludeTermsList.join(', ')}`
    : 'No exclusion terms specified'
}

EXECUTIVE SUMMARY:
This patent landscape analysis examines ${selectedSubjectsCount} technology area${
        selectedSubjectsCount !== 1 ? 's' : ''
      } to identify key patent trends, competitive positioning, and innovation opportunities.

KEY FINDINGS:

1. PATENT VOLUME ANALYSIS
   - Total relevant patents identified: 2,847
   - Filing trend: 15% increase over last 3 years
   - Geographic distribution: 45% US, 32% China, 12% Europe, 11% Other

2. TOP PATENT HOLDERS
   - Company A: 312 patents (11.0%)
   - Company B: 287 patents (10.1%)
   - Company C: 241 patents (8.5%)
   - Universities: 623 patents (21.9%)
   - Individual inventors: 178 patents (6.3%)

3. TECHNOLOGY CLUSTERS
   ${selectedSubjectNames
     .map(
       (subject) =>
         `   - ${subject}: ${Math.floor(Math.random() * 500 + 200)} patents`
     )
     .join('\n')}

4. INNOVATION GAPS
   - Emerging areas with low patent density identified
   - Potential white space opportunities in cross-technology applications
   - Recent surge in patents related to integration technologies

5. COMPETITIVE LANDSCAPE
   - High concentration in core technologies
   - Fragmented patent ownership in emerging areas
   - Strong university research presence indicates active R&D

RECOMMENDATIONS:
1. Monitor patent filings in identified white space areas
2. Consider strategic partnerships with key patent holders
3. Focus R&D efforts on underexplored technology intersections
4. Evaluate patent acquisition opportunities in complementary areas

METHODOLOGY:
- Search conducted across major patent databases
- Analysis period: 2019-2024
- Classification codes: Multiple IPC and CPC codes analyzed
- Quality filtering applied to exclude low-relevance patents
${
  excludeTermsList.length > 0
    ? `- Exclusion filtering removed patents containing: ${excludeTermsList.join(
        ', '
      )}`
    : ''
}

This analysis provides a foundation for strategic patent planning and competitive intelligence.

---
Report generated by Patent Landscape Analysis System`;

    case 'taxonomy':
      return `TAXONOMY ANALYSIS REPORT
Generated: ${timestamp}

ANALYSIS SCOPE:
Subjects Analyzed: ${selectedSubjectNames.join(', ')}

EXECUTIVE SUMMARY:
This taxonomy analysis provides definitions, related terms, and relationships for ${selectedSubjectsCount} subject${
        selectedSubjectsCount !== 1 ? 's' : ''
      } within the FS Taxonomy and other structured classification systems.

SUBJECT DEFINITIONS AND RELATIONSHIPS:

${selectedSubjectNames
  .map(
    (subject) =>
      `${subject.toUpperCase()}:
   Definition: Advanced technology domain focused on ${subject.toLowerCase()} applications and methodologies
   Related Terms: [Auto-generated based on taxonomy analysis]
   Classification: Level 2 Technology Category
   Parent Categories: Technology, Innovation, Research
   Child Categories: [Specific subcategories identified]
   Cross-references: Connected to ${Math.floor(
     Math.random() * 5 + 2
   )} related domains`
  )
  .join('\n\n')}

TAXONOMY STRUCTURE:
1. Primary Classifications
2. Secondary Relationships
3. Cross-domain Connections
4. Emerging Category Trends

STRUCTURED SOURCE COMPARISON:
- FS Taxonomy alignment: 87% coverage
- Industry standard taxonomies: 92% compatibility
- Academic classification systems: 78% overlap
- Government category frameworks: 83% match

RECOMMENDATIONS:
1. Standardize terminology across identified subjects
2. Develop clear hierarchical relationships
3. Monitor emerging classification trends
4. Maintain taxonomy currency with industry evolution

---
Report generated by Taxonomy Analysis System`;

    case 'research':
      return `RESEARCH LANDSCAPE ANALYSIS REPORT
Generated: ${timestamp}

ANALYSIS SCOPE:
Subjects Analyzed: ${selectedSubjectNames.join(', ')}
${
  excludeTermsList.length > 0
    ? `Excluded Terms: ${excludeTermsList.join(', ')}`
    : 'No exclusion terms specified'
}

EXECUTIVE SUMMARY:
This research landscape analysis examines scientific publishing trends across ${selectedSubjectsCount} subject area${
        selectedSubjectsCount !== 1 ? 's' : ''
      } to identify research patterns, key institutions, and emerging topics.

KEY FINDINGS:

1. PUBLICATION VOLUME ANALYSIS
   - Total relevant papers identified: 15,423
   - Publishing trend: 22% increase over last 5 years
   - Average citations per paper: 12.4
   - Open access percentage: 67%

2. TOP RESEARCH INSTITUTIONS
   - MIT: 1,247 papers (8.1%)
   - Stanford University: 1,156 papers (7.5%)
   - University of California System: 987 papers (6.4%)
   - Carnegie Mellon University: 834 papers (5.4%)
   - International collaborations: 2,341 papers (15.2%)

3. RESEARCH FOCUS AREAS
   ${selectedSubjectNames
     .map(
       (subject) =>
         `   - ${subject}: ${Math.floor(
           Math.random() * 3000 + 1000
         )} papers, avg ${Math.floor(Math.random() * 20 + 5)} citations`
     )
     .join('\n')}

4. EMERGING RESEARCH TRENDS
   - Interdisciplinary approaches showing 35% growth
   - Industry-academia collaborations increasing
   - Focus shift toward practical applications
   - Rise in reproducibility studies

5. PUBLICATION PATTERNS
   - Peak publishing months: March, September, November
   - Conference vs journal ratio: 60:40
   - International collaboration rate: 34%
   - Average time from submission to publication: 8.2 months

RESEARCH GAPS AND OPPORTUNITIES:
1. Underexplored intersections between subjects
2. Limited longitudinal studies identified
3. Geographic research distribution imbalances
4. Potential for novel methodology applications

METHODOLOGY:
- Search conducted across academic databases (PubMed, arXiv, IEEE, ACM)
- Analysis period: 2019-2024
- Quality filtering for peer-reviewed publications
- Citation analysis using multiple metrics
${
  excludeTermsList.length > 0
    ? `- Exclusion filtering removed papers containing: ${excludeTermsList.join(
        ', '
      )}`
    : ''
}

---
Report generated by Research Landscape Analysis System`;

    case 'investment':
      return `INVESTMENT ANALYSIS REPORT
Generated: ${timestamp}

ANALYSIS SCOPE:
Subjects Analyzed: ${selectedSubjectNames.join(', ')}
${
  excludeTermsList.length > 0
    ? `Excluded Terms: ${excludeTermsList.join(', ')}`
    : 'No exclusion terms specified'
}

EXECUTIVE SUMMARY:
This investment analysis examines venture capital and funding trends across companies operating in ${selectedSubjectsCount} technology area${
        selectedSubjectsCount !== 1 ? 's' : ''
      }.

KEY FINDINGS:

1. INVESTMENT VOLUME ANALYSIS
   - Total funding identified: $24.7B across 2,156 companies
   - Average deal size: $11.5M
   - Year-over-year growth: 18% increase in total funding
   - Active investors: 1,247 firms

2. TOP INVESTORS BY VOLUME
   - Andreessen Horowitz: $1.2B across 47 deals
   - Sequoia Capital: $987M across 34 deals
   - Google Ventures: $834M across 52 deals
   - Intel Capital: $723M across 28 deals
   - Strategic corporate investors: $8.9B (36% of total)

3. INVESTMENT BY SUBJECT AREA
   ${selectedSubjectNames
     .map(
       (subject) =>
         `   - ${subject}: $${(Math.random() * 5 + 1).toFixed(
           1
         )}B across ${Math.floor(Math.random() * 300 + 100)} companies`
     )
     .join('\n')}

4. FUNDING STAGE DISTRIBUTION
   - Seed/Pre-seed: 34% of deals, $892M total
   - Series A: 28% of deals, $4.2B total
   - Series B: 18% of deals, $6.1B total
   - Series C+: 12% of deals, $9.8B total
   - Late stage/Growth: 8% of deals, $3.7B total

5. GEOGRAPHIC DISTRIBUTION
   - Silicon Valley: 42% of total funding
   - New York: 18% of total funding
   - Boston: 12% of total funding
   - International: 28% of total funding

MARKET TRENDS:
1. Increased focus on AI integration across all sectors
2. Sustainability and ESG considerations gaining importance
3. Corporate venture capital participation growing
4. Longer time to exit but higher valuations

INVESTMENT OPPORTUNITIES:
1. Early-stage companies in emerging intersections
2. B2B solutions showing strong traction
3. International expansion opportunities
4. Acquisition targets for strategic buyers

RISK FACTORS:
1. Market saturation in core areas
2. Regulatory uncertainty in emerging technologies
3. Talent acquisition competition
4. Economic sensitivity of growth-stage companies

METHODOLOGY:
- Data sourced from Crunchbase, PitchBook, and public filings
- Analysis period: 2019-2024
- Includes venture capital, growth equity, and strategic investments
- Private company valuations estimated where not disclosed
${
  excludeTermsList.length > 0
    ? `- Exclusion filtering removed companies containing: ${excludeTermsList.join(
        ', '
      )}`
    : ''
}

---
Report generated by Investment Analysis System`;

    default:
      return 'Error: Unknown analysis type';
  }
};
